#!/bin/bash

set -e
set -u

echo 'START'

echo '$SHOP_POSTGRES_USER'
echo '$SHOP_POSTGRES_PASSWORD'

psql -v ON_ERROR_STOP=1 <<-EOSQL
CREATE USER $SHOP_POSTGRES_USER WITH
    LOGIN
    SUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD '$SHOP_POSTGRES_PASSWORD';

CREATE DATABASE $SHOP_POSTGRES_DB
    WITH
    OWNER = $SHOP_POSTGRES_USER
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    TEMPLATE = template0;

\connect $SHOP_POSTGRES_DB;

CREATE SCHEMA IF NOT EXISTS $SHOP_POSTGRES_DB_SCHEMA AUTHORIZATION $SHOP_POSTGRES_USER;
CREATE SCHEMA IF NOT EXISTS liquibase AUTHORIZATION $SHOP_POSTGRES_USER;

EOSQL

echo 'DONE'
