server:
  port: ${APPLICATION_PORT:8080}
  address: 0.0.0.0
  error:
    include-stacktrace: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://127.0.0.1:5432/shop?ApplicationName=SHOP}
    username: ${JDBC_USERNAME:shop}
    password: ${JDBC_PASSWORD:shop}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_COMMITTED

#jwt:
#  secret: UyJUnQZH5YYLw9vjsyb4R6nY85rPCNNk
