/*
 * This file is generated by jOOQ.
 */
package com.github.kreker721425.shop.db.tables.pojos;


import java.io.Serializable;


/**
 * Состав заказа
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long productId;
    private Long orderId;
    private Long count;

    public ProductOrder() {}

    public ProductOrder(ProductOrder value) {
        this.productId = value.productId;
        this.orderId = value.orderId;
        this.count = value.count;
    }

    public ProductOrder(
        Long productId,
        Long orderId,
        Long count
    ) {
        this.productId = productId;
        this.orderId = orderId;
        this.count = count;
    }

    /**
     * Getter for <code>shop.product_order.product_id</code>. Идентификатор продукта
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>shop.product_order.product_id</code>. Идентификатор продукта
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>shop.product_order.order_id</code>. Идентификатор заказа
     */
    public Long getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>shop.product_order.order_id</code>. Идентификатор заказа
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>shop.product_order.count</code>. Количество продукта в заказе
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>shop.product_order.count</code>. Количество продукта в заказе
     */
    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductOrder (");

        sb.append(productId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
