/*
 * This file is generated by jOOQ.
 */
package com.github.kreker721425.shop.db.enums;


import com.github.kreker721425.shop.db.Shop;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TableEnum implements EnumType {

    CLIENT("CLIENT"),

    ORDER("ORDER"),

    USER("USER"),

    PRODUCT("PRODUCT");

    private final String literal;

    private TableEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Shop.SHOP;
    }

    @Override
    public String getName() {
        return "table_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
