version: '3'

services:
  shop_postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
    environment:
      SHOP_POSTGRES_USER: shop
      SHOP_POSTGRES_PASSWORD: shop
      SHOP_POSTGRES_DB: shop
      SHOP_POSTGRES_DB_SCHEMA: shop
    container_name: shop_postgres_5432