spring:
  liquibase:
    change-log: "classpath:/liquibase/dbschema/master.xml"
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/shop?ApplicationName=SHOP
    username: shop
    password: shop
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_COMMITTED