/*
 * This file is generated by jOOQ.
 */
package com.github.kreker721425.shop.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in shop.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>shop.client_id_seq</code>
     */
    public static final Sequence<Long> CLIENT_ID_SEQ = Internal.createSequence("client_id_seq", Shop.SHOP, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>shop.order_id_seq</code>
     */
    public static final Sequence<Long> ORDER_ID_SEQ = Internal.createSequence("order_id_seq", Shop.SHOP, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>shop.product_id_seq</code>
     */
    public static final Sequence<Long> PRODUCT_ID_SEQ = Internal.createSequence("product_id_seq", Shop.SHOP, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
