/*
 * This file is generated by jOOQ.
 */
package com.github.kreker721425.shop.db;


import com.github.kreker721425.shop.db.tables.Client;
import com.github.kreker721425.shop.db.tables.Order;
import com.github.kreker721425.shop.db.tables.Product;
import com.github.kreker721425.shop.db.tables.ProductOrder;


/**
 * Convenience access to all tables in shop.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Клиенты
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * Заказ
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * Продукты
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * Состав заказа
     */
    public static final ProductOrder PRODUCT_ORDER = ProductOrder.PRODUCT_ORDER;
}
