/*
 * This file is generated by jOOQ.
 */
package com.github.kreker721425.shop.db;


import com.github.kreker721425.shop.db.tables.Client;
import com.github.kreker721425.shop.db.tables.History;
import com.github.kreker721425.shop.db.tables.Order;
import com.github.kreker721425.shop.db.tables.Product;
import com.github.kreker721425.shop.db.tables.ProductOrder;
import com.github.kreker721425.shop.db.tables.Users;


/**
 * Convenience access to all tables in shop.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Клиент
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * История операций
     */
    public static final History HISTORY = History.HISTORY;

    /**
     * Заказ
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * Продукт
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * Состав заказа
     */
    public static final ProductOrder PRODUCT_ORDER = ProductOrder.PRODUCT_ORDER;

    /**
     * Пользователь
     */
    public static final Users USERS = Users.USERS;
}
